### ISSUE TITLE
opsec way to collect

### ISSUE THREAD

**Issue by seventeenman** [ly4k/Certipy#100]
Is there any opsec way to collect the ca template name?

I just need this name, no need to do any information gathering
[*] Trying to get CA configuration for 'red-DC-CA-1' via CSRA

**Comment by seventeenman** [comment]
Seems like he's going to do something about BloodHound anyway hahaha

**Comment by ly4k** [comment]
Hello. Currently there are no options like this for Certipy. In order to find the CA name and address, Certipy must extract it from LDAP. At the moment, I'm not planning on modifying Certipy to accommodate this requirement as I simply don't have the time.

Best regards
