### ISSUE TITLE
Error: "bind context rejected: invalid_checksum"

### ISSUE THREAD

**Issue by 7MinSec** [ly4k/Certipy#101]
Hello!

I'm working with a ADCS environment vulnerable to ESC1.  When I queue up my command...

`certipy req -username@domain.com -p 'mypass' -ca 'Name of CA' -target fqdn.of.the.ca -template VulnTemplate -dc-ip 1.2.3.4 -debug`

I get:

`Got error: Bind context rejected: invalid_checksum`

Any idea what this indicates?  My Google-Fu isn't finding much.

**Comment by 7MinSec** [comment]
Ohhhhh and JUST after posting this I think I have the fix.  I first used `gettgt.py` from [impacket](https://github.com/SecureAuthCorp/impacket) to get Kerberos auth going:

````
gettgt.py domain.com/username
export KRB5CCNAME=username.ccache
````

Then did the same `certipy req` command but this time with `-k` instead of `-username@blahblahblah` and I think I'm good to go!  Will report back when I know for sure.

**Comment by 7MinSec** [comment]
Aaaaaand that was it!  Kerberos auth made things happy again.  Have a wonderful day!

**Comment by BlWasp** [comment]
Da** you save me so much time guy ! Thanks for the issue and the solution !
