### ISSUE TITLE
 certipy shadow: KDC_ERR_PADATA_TYPE_NOSUPP(KDC has no support for padata type)

### ISSUE THREAD

**Issue by kamikazejunk** [ly4k/Certipy#139]
I got error while running certipy. I am asking because these seems no way to save pfx file and use PassTheCert.exe..... 

certipy shadow auto -dc-ip ip -username username@target.local -p "pass"  -account victim-accout

[-] Got error while trying to request TGT: Kerberos SessionError: KDC_ERR_PADATA_TYPE_NOSUPP(KDC has no support for padata type)

**Comment by ly4k** [comment]
You can use "shadow add" instead of auto. Auto will add, authenticate and remove it after. However, the error you get seems to be related to the DC not having a certificate for Kerberos authentication
