### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by fabaff** [ly4k/Certipy#14]
Could you please tag the source? This allows distributions to get the complete source from GitHub and version the packages properly (e.g., https://github.com/NixOS/nixpkgs/pull/145126).

Thanks

**Comment by fabaff** [comment]
@ly4k, looks like that you missed to push the tag :wink:

**Comment by ly4k** [comment]
I'm expecting to publish a major release on Saturday. I will tag that release.

**Comment by ly4k** [comment]
@fabaff should be tagged now with the new version

**Comment by fabaff** [comment]
@ly4k , thanks a lot.
