### ISSUE TITLE
LDAPInvalidCredentialsResult - 49 - invalidCredentials. Shadow Credentials -> Schannel -> ldap_shell

### ISSUE THREAD

**Issue by xfusion13** [ly4k/Certipy#144]
Greetings! I want to connect to LDAP having a .pfx obtained through the `shadow add` module. But the `auth` module gives:
**Got error: LDAPInvalidCredentialsResult - 49 - invalidCredentials**. 
![Pasted image 20230501182609](https://user-images.githubusercontent.com/51033610/235493488-26499b1d-a770-4388-be2b-36fda3c60221.png)
![Pasted image 20230501184227](https://user-images.githubusercontent.com/51033610/235493648-416ce581-c0e2-4278-9d42-b05da98be75d.png)
Moreover, if you request a certificate via `req`, then ldap_shell works.
![Pasted image 20230501184849](https://user-images.githubusercontent.com/51033610/235493789-0ec44bdf-13b3-4b8e-9df3-036a62751864.png)
Thanks!

**Comment by ly4k** [comment]
In my own testing, Shadow Credentials do not work with LDAP Schannel. I haven't figured out how to make it work. Perhaps it will work in newer/updated environments where SChannel uses Kerberos for certificate mapping.
