### ISSUE TITLE
Got error: module 'enum' has no attribute '_decompose'

### ISSUE THREAD

**Issue by probablypablito** [ly4k/Certipy#154]
This happened during an active HTB machine, so some info will be redacted.

The command ran was: `proxychains -q certipy find -vulnerable -target 127.0.0.1 -u 'user' -p 'P@ssw0rd' -debug`

At first I thought this might've been due to my use of proxychains, but after compiling to Windows using pyinstaller and running it directly on the DC I got the same result.

Here is the full output, ran on Kali Linux via the aforementioned command: [Pastebin](https://pastebin.com/raw/S7uiwFjY
)

EDIT: This seems to not occur with Python 3.10. Maybe the patch in https://github.com/ly4k/Certipy/pull/129 didn't work?

**Comment by ly4k** [comment]
I'm looking into this. It appears the problem isn't the _decompose call in the first place. It's because the new patch fails - perhaps due to a NoneType - which makes it fall back to the old implementation. I'll see what I can do :)

**Comment by jordanpkimball** [comment]
Replicated issue on 3.11 and verified that Python3.10 works as a temporary workaround for anyone who needs to get it working before Ly4k can get the patch out. Thanks @probablypablito for the edit on that for the workaround.

**Comment by secure-77** [comment]
If some else is running into this issue and don`t want to install python 3.10, I created a quick Docker Image to run it with python 3.10: https://github.com/secure-77/Certipy-Docker
