### ISSUE TITLE
What to do when cert reports as vulnerable with....NO vulnerabilities? 

### ISSUE THREAD

**Issue by 7MinSec** [ly4k/Certipy#155]
Hi,

I did a `certipy -find -vulnerable` for an org, and I get (sanitized) output like this:

```
Certificate Authorities
0
CA NAME: CA.DOMAIN.COM
DNS Name: CA.DOMAIN.COM
Certificate subject: Blah blah
Certificate serial number: blah
Cert validity start: Blah
Cert validity end: blah
Web enrollment: disabled
User specified SAN: unknown
Request disposition: unknown
Enforce encryption for requests: unknown
Certificate templates: Could not find any cert templates
```

I'll try poking at them as if they have ESC1, for example, but any ideas why this one would report as vulnerable but without any specific vulnerabilities?

**Comment by smokeintheshell** [comment]
Certipy always outputs the details of all identified Certificate Authorities, which is what you're showing. If no templates are returned then it did not identify any vulnerable templates.

**Comment by 7MinSec** [comment]
Ok thanks much!
