### ISSUE TITLE
ModuleNotFoundError: No module named 'certipy.command_line' when running certipy

### ISSUE THREAD

**Issue by CyberCJ1999** [ly4k/Certipy#166]
Traceback (most recent call last):
  File "/usr/bin/certipy", line 33, in <module>
    sys.exit(load_entry_point('certipy==0.1.3', 'console_scripts', 'certipy')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/certipy", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'certipy.command_line'

is this to do with the version of Python I am running?

**Comment by ly4k** [comment]
Looks like you installed the wrong Certipy. Try `pip install certipy-ad`

**Comment by CyberCJ1999** [comment]
pip install certipy-ad


i get the following:

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: certipy-ad in ./.local/lib/python3.11/site-packages (4.7.0)
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from certipy-ad) (1.5.1)
Requirement already satisfied: cryptography>=39.0 in ./.local/lib/python3.11/site-packages (from certipy-ad) (41.0.3)
Requirement already satisfied: impacket in /usr/lib/python3/dist-packages (from certipy-ad) (0.10.0)
Requirement already satisfied: ldap3 in /usr/lib/python3/dist-packages (from certipy-ad) (2.9.1)
Requirement already satisfied: pyasn1==0.4.8 in /usr/lib/python3/dist-packages (from certipy-ad) (0.4.8)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from certipy-ad) (2.3.0)
Requirement already satisfied: dsinternals in /usr/lib/python3/dist-packages (from certipy-ad) (1.2.4)
Requirement already satisfied: pyopenssl>=23.0.0 in /usr/lib/python3/dist-packages (from certipy-ad) (23.0.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from certipy-ad) (2.28.1)
Requirement already satisfied: requests-ntlm in ./.local/lib/python3.11/site-packages (from certipy-ad) (1.2.0)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.11/site-packages (from certipy-ad) (3.18.0)
Requirement already satisfied: unicrypto in /usr/lib/python3/dist-packages (from certipy-ad) (0.0.10)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography>=39.0->certipy-ad) (1.15.1)
Requirement already satisfied: pyspnego>=0.1.6 in /usr/lib/python3/dist-packages (from requests-ntlm->certipy-ad) (0.8.0)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from unicrypto->certipy-ad) (3.11.0)

**Comment by CyberCJ1999** [comment]
when i was trying to load certipy-ad, i would get the following


Command 'certipy-ad' not found, but can be installed with:
sudo apt install certipy-ad
Do you want to install it? (N/y)y
sudo apt install certipy-ad
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  certipy-ad
0 upgraded, 1 newly installed, 0 to remove and 1147 not upgraded.
Need to get 93.2 kB of archives.
After this operation, 551 kB of additional disk space will be used.
Get:1 http://mirror.vinehost.net/kali kali-rolling/main amd64 certipy-ad all 4.7.0-0kali3 [93.2 kB]
Fetched 93.2 kB in 13s (7,336 B/s)    
(Reading database ... 418974 files and directories currently installed.)
Preparing to unpack .../certipy-ad_4.7.0-0kali3_all.deb ...
Unpacking certipy-ad (4.7.0-0kali3) ...
dpkg: error processing archive /var/cache/apt/archives/certipy-ad_4.7.0-0kali3_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/certipy/__init__.py', which is also in package python3-certipy 0.1.3-4
Errors were encountered while processing:
 /var/cache/apt/archives/certipy-ad_4.7.0-0kali3_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by CyberCJ1999** [comment]
i am going to try and delete /certipy-ad_4.7.0-0kali3_all.deb directory from archives and run sudo apt-get upgrade to download a fresh copy

**Comment by CyberCJ1999** [comment]
certipy-ad seems to have successfully uninstalled

pip uninstall certipy-ad                  
WARNING: Skipping certipy-ad as it is not installed.

**Comment by CyberCJ1999** [comment]
attempt to install pip like you suggested

pip install certipy-ad  
Defaulting to user installation because normal site-packages is not writeable
Collecting certipy-ad
  Obtaining dependency information for certipy-ad from https://files.pythonhosted.org/packages/ed/e3/c08ca4c4098d91e84bf637b0c3e83de7e396243191cec36c0be9c572742e/certipy_ad-4.8.0-py3-none-any.whl.metadata
  Using cached certipy_ad-4.8.0-py3-none-any.whl.metadata (42 kB)
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from certipy-ad) (1.5.1)
Requirement already satisfied: cryptography>=39.0 in ./.local/lib/python3.11/site-packages (from certipy-ad) (41.0.3)
Requirement already satisfied: impacket in /usr/lib/python3/dist-packages (from certipy-ad) (0.11.0)
Requirement already satisfied: ldap3 in /usr/lib/python3/dist-packages (from certipy-ad) (2.9.1)
Requirement already satisfied: pyasn1==0.4.8 in /usr/lib/python3/dist-packages (from certipy-ad) (0.4.8)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from certipy-ad) (2.4.2)
Requirement already satisfied: dsinternals in /usr/lib/python3/dist-packages (from certipy-ad) (1.2.4)
Requirement already satisfied: pyopenssl>=23.0.0 in /usr/lib/python3/dist-packages (from certipy-ad) (23.0.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from certipy-ad) (2.31.0)
Requirement already satisfied: requests-ntlm in ./.local/lib/python3.11/site-packages (from certipy-ad) (1.2.0)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.11/site-packages (from certipy-ad) (3.18.0)
Requirement already satisfied: unicrypto in /usr/lib/python3/dist-packages (from certipy-ad) (0.0.10)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography>=39.0->certipy-ad) (1.15.1)
Requirement already satisfied: pyspnego>=0.1.6 in /usr/lib/python3/dist-packages (from requests-ntlm->certipy-ad) (0.8.0)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from unicrypto->certipy-ad) (3.11.0)
Using cached certipy_ad-4.8.0-py3-none-any.whl (130 kB)
Installing collected packages: certipy-ad
  WARNING: The script certipy is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                       
Successfully installed certipy-ad-4.8.0

**Comment by CyberCJ1999** [comment]
'/home/kali/.local/bin' added to PATH

certipy is now working

thank you so so much
