### ISSUE TITLE
certipy: error: unrecognized arguments: ESC7 

### ISSUE THREAD

**Issue by kali64amd** [ly4k/Certipy#186]
I'm clueless on this error ......... appreciate any insight !!!

certipy ca -ca 'XYZ-DC01-CA' -add-officer raven -username 'raven@xyz.htb' -password 'password123' -target xyz.htb 

certipy: error: unrecognized arguments: certipy ca -ca 'XYZ-DC01-CA' -add-officer raven -username 'raven@xyz.htb' -password 'password123' -target xyz.htb 

bug??

**Comment by kali64amd** [comment]
└─$ pip3 install certipy-ad
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/auto_py_to_exe-2.34.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/pyinstaller-5.10.1-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: certipy-ad in /usr/lib/python3/dist-packages (4.7.0)
                                                                                                                                                                      
┌──(shinobix㉿shinobix)-[~]
└─$ pip --version
pip 23.3 from /usr/lib/python3/dist-packages/pip (python 3.11)


┌──(shinobix㉿shinobix)-[~]
└─$ certipy-ad  -v
Certipy v4.7.0 - by Oliver Lyak (ly4k)

**Comment by ly4k** [comment]
You have the wrong Certipy installed. `pip3 uninstall certipy` and then reinstall the correct one.
