### ISSUE TITLE
The requested certificate template is not supported by this CA.

### ISSUE THREAD

**Issue by helloyw** [ly4k/Certipy#191]
This error occurred when I was using ESC4，By using the command - vulnerable, it can be determined that the template has an ESC4 vulnerability

```
certipy req -username test@test.com -password "password@123" -ca DC1-CA -target DC1.test.com -template HorizonV8 -upn administrator@test.com -dns-tcp -ns 172.16.12.8
Certipy v4.8.2 - by Oliver Lyak (ly4k)

[] Requesting certificate via RPC
[-] Got error while trying to request certificate: code: 0x80094800 - CERTSRV_E_UNSUPPORTED_CERT_TYPE - The requested certificate template is not supported by this CA.
[] Request ID is 129
Would you like to save the private key? (y/N) n
[-] Failed to request certificate

```

**Comment by at0mman** [comment]
This is mostly because the certificate template you are using is not enabled. Run the certipy find command again with -enabled to get only enabled certificates.

**Comment by helloyw** [comment]
> This is mostly because the certificate template you are using is not enabled. Run the certipy find command again with -enabled to get only enabled certificates.

But I used this template to successfully apply for the pfx certificate using esc1.

**Comment by helloyw** [comment]
Looking forward to your reply again

**Comment by h4ckd0tm3** [comment]
See https://github.com/ly4k/Certipy/issues/189#issuecomment-1908163430

**Comment by helloyw** [comment]
> 参见[#189（评论）](https://github.com/ly4k/Certipy/issues/189#issuecomment-1908163430)

Do you have detailed usage instructions for reference? Thank you for your reply
