### ISSUE TITLE
Which abuse scenarious are supported by this tool?

### ISSUE THREAD

**Issue by jsdhasfeds** [ly4k/Certipy#2]
Hi. Thank you very much for your effort writing this tool. I have successfully used it in the scenarios with technique IDs ESC1 and ESC2 in Will Schroeder's and Lee Christensen's whitepaper. Both manually and automatically. I have a few questions:

1) In automatic mode, can you force the use of a specific certificate template? This is not really needed but could be valuable in penetration testing reports in order to "prove" that specific templates are vulnerable. I could of course abuse them manually but now that your tool has this nice automatic feature I want to use that :)

2) Which other scenarious are supported by this tool? For example  technique ID ESC6. If not, are you planning to implement this? FYI. Certi.py does not support ESC6 which forces you to use Rubeus on a domain-joined machine which is far from optimal and not something I really want to do.

**Comment by ly4k** [comment]
ESC1, ESC2, ESC3, ESC4, ESC6, ESC7, and ESC8 are supported in the new version of Certipy.
