### ISSUE TITLE
Help determining if ESC8 vulnerability is false positive?

### ISSUE THREAD

**Issue by 7MinSec** [ly4k/Certipy#202]
Hello!

On a test I've found a config reporting vulnerable to ESC8.  I setup `certipy relay -target vulnca.domain.com` when I try to coerce from a DC with `coerce -u user -p pass -t ip.of.a.dc -l my.attacking.kali.ip` my smb.log is filled with entries like:

```
Received connection from DOMAIN/DC$ at DC01$, connection will be relayed after re-authentication
```

Any ideas of what's going on here?  Not sure what to try next.

**Comment by fgeek** [comment]
In ESC8 you should be relaying to the ADCS CA server, not DC. Remember to define the affected template. It should work with hostname instead of IP, but try both if one does not work.

https://github.com/ly4k/Certipy?tab=readme-ov-file#esc8

**Comment by 7MinSec** [comment]
Ah geez thank you...I think I was up too late working on this and not defining targets right.  I'll give it another dance once I've had some sleep :-)

**Comment by 7MinSec** [comment]
OK I got things reconfigured and the relay is happening but not successful.  I got a second opinion through ntlmrelayx and I'm getting "No NTLM challenge returned from server" so I'm thinking they've hardened the config?

**Comment by cmjlove1** [comment]
> OK I got things reconfigured and the relay is happening but not successful. I got a second opinion through ntlmrelayx and I'm getting "No NTLM challenge returned from server" so I'm thinking they've hardened the config?好的，我重新配置了东西，继电器正在发生，但没有成功。我通过 ntlmrelayx 获得了第二意见，并且收到“服务器未返回 NTLM 挑战”，所以我认为他们已经强化了配置？

Yes, this is because ADCS's Windows authentication is set to Negotiate:Kerberos.
![image](https://github.com/user-attachments/assets/6bd9e0a9-4687-41e2-be68-fd7470c0c61e)

Because ESC8 is NTLM relay, it will not succeed.
You can use [RemoteKrbrelay](https://github.com/CICADA8-Research/RemoteKrbRelay) for Kerberos relay attacks.

**Comment by 7MinSec** [comment]
Ok thank you much everybody!
