### ISSUE TITLE
ValueError: nameserver None is not an IP address or valid https URL

### ISSUE THREAD

**Issue by proyecto-gemyn** [ly4k/Certipy#26]
Hello! 
I'm trying to dump the AD with bloodhound and the find action, but I have this error.
Tested on a recently install Kali Linux 2022.1 with Python 3.9.10

-] Got error: nameserver None is not an IP address or valid https URL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 982, in nameservers
    raise NotImplementedError
NotImplementedError

and the command is:
certipy find 'domain/user:pass@192.X.X.X' -debug -bloodhound
I have tried with thr fqdn and name only of the DC with the same results. If I ping using the names, works without issues.

Thanks in advance.

**Comment by ly4k** [comment]
Fixing this later today. Thanks!

**Comment by ly4k** [comment]
Should be fixed in 2.0.2. Will you please check, when you have time?

**Comment by proyecto-gemyn** [comment]
I've pulled the new version, now it works, but I have an issue with the LDAP not accepting SSL connection, probably because it hasn't been properly configured, it is and old W2012 server btw.

Thanks!

**Comment by ly4k** [comment]
Try with `-scheme ldap`

**Comment by proyecto-gemyn** [comment]
f**k yeah! Thanks for the tip!
