### ISSUE TITLE
ESC8 - Error when requesting the NT hash of a DC's machine account

### ISSUE THREAD

**Issue by jsdhasfedssad** [ly4k/Certipy#32]
I successfully used Certipy 2.0.6 and Dementor to execute the ESC8 attack relaying authentication from a DC to ADCS. Once I got the certificate for the DC's machine account I used that to request the NT hash of the machine account. This works as long as I do not use the flag "-ns 10.0.0.200". This is strange since I have to use that flag when executing more or less all other Certipy commands.
![esc8](https://user-images.githubusercontent.com/97032878/155489164-19449a1b-6467-49c2-8b7a-1a79f56df7e8.png)

The error message suggests this happens due to some temporary network hickup or that the DNS service is down but that is not the case.

**Comment by ly4k** [comment]
Thanks for reporting this. Should be fixed in the latest commit (not version). Can you please verify?

**Comment by jsdhasfedssad** [comment]
I tested this in 2.0.8 but I get what looks like the same error.
![esc8_2](https://user-images.githubusercontent.com/97032878/155691586-01377cdb-271f-4958-994e-7b38e762bb8d.png)

**Comment by ly4k** [comment]
Should be fixed now in 2.0.9. Forgot to resolve the domain name, if `ns` was supplied. Can you verify?

**Comment by jsdhasfedssad** [comment]
Super. This is working now.

**Comment by ly4k** [comment]
Great!
