### ISSUE TITLE
error: SandboxViolation

### ISSUE THREAD

**Issue by liayou9** [ly4k/Certipy#35]
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/root/Library/Caches/com.apple.python/private/tmp/easy_install-qii5l5tu', 511) {}

**Comment by ly4k** [comment]
How did you install it? You can try with the `--user` flag

**Comment by liayou9** [comment]
My computer is mac m1, I don't know if it is a problem with arm? I don't have this problem with ubuntu。
<img width="747" alt="Screen Shot 2022-03-09 at 9 32 22 AM" src="https://user-images.githubusercontent.com/40752745/157354950-a9118391-3831-43eb-92e5-2c6988f5728b.png">

**Comment by ly4k** [comment]
Please try `python3 setup.py install --user`. Googling the issue gives similar results that indicate it might be a problem with your Python environment.

**Comment by liayou9** [comment]
Tried ```python3 setup.py install --user``` still the same error message, it may be the problem of arm, but thank you anyway

**Comment by ly4k** [comment]
Don't think it's an issue related to the processor architecture, but rather that you are using a Mac. Not sure how to fix the issue. Can you try to upgrade python's setuptools? Or perhaps try `pip install .`

**Comment by liayou9** [comment]
This time the installation did not report an error, but starting certipy will report an error

<img width="744" alt="Screen Shot 2022-03-11 at 9 35 45 AM" src="https://user-images.githubusercontent.com/40752745/157785071-5ad2fb05-52b4-4d3a-ae6f-1d30b64b7eae.png">

**Comment by ly4k** [comment]
Try with pip3 instead of pip

**Comment by liayou9** [comment]
```pip3 install .```That doesn't work either,
![Screen Shot 2022-03-14 at 10 34 19 AM](https://user-images.githubusercontent.com/40752745/158095157-33f6e6bb-59b8-4689-8da7-9749168b57bd.png)

**Comment by ly4k** [comment]
You need to run as sudo er with --user

**Comment by liayou9** [comment]
The problem is finally solved, thank you very much

**Comment by kidandcat** [comment]
Just to have it documented. I had the same error (even using sudo) and I could fix it by using homebrew python3 version. (it fails with the native macos python3)
