### ISSUE TITLE
ESC1 error code：0x80070057

### ISSUE THREAD

**Issue by liayou9** [ly4k/Certipy#36]
<img width="863" alt="屏幕截图 2022-03-08 163925" src="https://user-images.githubusercontent.com/40752745/157199895-2eedd056-bb2f-439a-880d-5177b25d1b59.png">

**Comment by ly4k** [comment]
This error happens because the CA `corp-CA` specified in your command doesn't match the name of the CA. You should find the name of the CA you want to enroll in rather than the on. You can use the `certipy find` to find the name of the CA

**Comment by liayou9** [comment]
Problem solved, thank you very much
