### ISSUE TITLE
Unable to request certificate due to key archival 

### ISSUE THREAD

**Issue by bandrel** [ly4k/Certipy#41]
Any idea if there is a way around this or is the template not vulnerable if the private key is stored in AD?

[-] Got error while trying to request certificate: code: 0x80094804 - CERTSRV_E_ARCHIVED_KEY_REQUIRED - The request is missing a required private key for archival by the server.

**Comment by bandrel** [comment]
![image](https://user-images.githubusercontent.com/3598052/162233497-b3fa593d-0834-42be-9e8f-b57651efb556.png)
![image](https://user-images.githubusercontent.com/3598052/162233618-1db2508d-f463-446a-a029-c700aadd4fc5.png)

**Comment by ly4k** [comment]
Hello. There should be a way to send the private key during the request for key archival. I'm currently having trouble to add the private key into the structures for the certificate request as these should be in one request. I'll try to add it for the next release of Certipy :-)

**Comment by ly4k** [comment]
Hello @bandrel I have managed to implement this feature into the upcoming version of Certipy. It was tons of work, but I think it's a nice feature to have! So thanks for reporting this :)

**Comment by ly4k** [comment]
Fixed in https://github.com/ly4k/Certipy/commit/defd7f458d8287ed4dc72c5d3164e507d2df3bd9
