### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by extremepaperclip** [ly4k/Certipy#42]
CertiPy install works perfectly on any Kali VM, but when I try to install it on a Ubuntu 18.04 or CentOS 7 VM I get this error:

ModuleNotFoundError: No module named 'setuptools_rust'

Let me know if this is something known already, and if so - what is the fix?

Thanks!

**Comment by ly4k** [comment]
Can you try to install with "pip3 install ." within the folder

**Comment by extremepaperclip** [comment]
Installing via "pip install Certipy"  looks like it installed Certipy-0.1.3.
Is that the correct version?

**Comment by ly4k** [comment]
That's another package called Certipy. You should run "pip3 install ." from the source root folder
