### ISSUE TITLE
RequestSessionError: code: 0x80070057 - E_INVALIDARG - One or more arguments are invalid

### ISSUE THREAD

**Issue by howtogetfish** [ly4k/Certipy#46]
[*] Requesting certificate
[-] Got error: RequestSessionError: code: 0x80070057 - E_INVALIDARG - One or more arguments are invalid.
[-] Use -debug to print a stacktrace
![image](https://user-images.githubusercontent.com/59220217/168328946-1b7d1c2d-1a85-423e-ab7b-d9c39dcf5ce3.png)

Has the boss ever reported this error

**Comment by npy0921** [comment]
老哥，心照不宣，此时此刻，我也遇见这个问题

**Comment by howtogetfish** [comment]
> 

我怀疑脚本对python版本有兼容问题

**Comment by npy0921** [comment]
换个python版本试试

**Comment by npy0921** [comment]
老哥，你解决这个问题了吗

**Comment by npy0921** [comment]
老哥，我刚找到问题了，应该是CA写的不对 写具体的名字就好了

**Comment by howtogetfish** [comment]
老哥起那么早，我昨天改过CA名称
要不截个图看看

**Comment by npy0921** [comment]
![image](https://user-images.githubusercontent.com/62608697/168407344-85e2b0cc-cf58-48f4-8402-da47c2cc36cd.png)
![image](https://user-images.githubusercontent.com/62608697/168407370-0d800331-e1a5-4c13-ac1c-1201312b7c4b.png)

**Comment by howtogetfish** [comment]
新坑
![image](https://user-images.githubusercontent.com/59220217/168408185-ce4e5ea4-0dde-489e-a2b3-19162d22bfae.png)

**Comment by howtogetfish** [comment]
新坑
![image](https://user-images.githubusercontent.com/59220217/168408200-8db80d34-0968-4327-aece-a2e9fc68c1ff.png)

**Comment by npy0921** [comment]
直接执行这个试试    certipy auth -pfx XXX.pfx

**Comment by howtogetfish** [comment]
复现完了
谢谢老哥
certipy auth -pfx dc.pfx -username DC\$ -domain xx.com -dc-ip 192.168.1.1

**Comment by npy0921** [comment]
OKOK
