### ISSUE TITLE
No Module Name certipy.entry

### ISSUE THREAD

**Issue by rehan994** [ly4k/Certipy#52]
During the start of certipy below error appear . Any one help me out on this

Traceback (most recent call last):
  File "/usr/local/bin/certipy", line 5, in <module>
    from certipy.entry import main
ModuleNotFoundError: No module named 'certipy.entry'

**Comment by ly4k** [comment]
Have you tried to install with "pip3 install /path/to/Certipy"

**Comment by rehan994** [comment]
yes i had installed by using below command :
pip3 install .

Output
==================================================================================
└─# pip install .      
Processing /root/Desktop/Certipy
Requirement already satisfied: asn1crypto in /usr/lib/python3/dist-packages (from Certipy==3.0.0) (1.4.0)
Requirement already satisfied: cryptography>=3.5 in /usr/local/lib/python3.9/dist-packages/cryptography-37.0.2-py3.9-linux-x86_64.egg (from Certipy==3.0.0) (37.0.2)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from Certipy==3.0.0) (2.0.0)
Requirement already satisfied: dsinternals in /usr/local/lib/python3.9/dist-packages/dsinternals-1.2.4-py3.9.egg (from Certipy==3.0.0) (1.2.4)
Requirement already satisfied: impacket in /usr/lib/python3/dist-packages (from Certipy==3.0.0) (0.9.24)
Requirement already satisfied: ldap3 in /usr/lib/python3/dist-packages (from Certipy==3.0.0) (2.8.1)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from Certipy==3.0.0) (0.4.8)
Requirement already satisfied: pyopenssl>=22.0.0 in /usr/local/lib/python3.9/dist-packages/pyOpenSSL-22.0.0-py3.9.egg (from Certipy==3.0.0) (22.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3/dist-packages (from cryptography>=3.5->Certipy==3.0.0) (1.14.6)
Building wheels for collected packages: Certipy
  Building wheel for Certipy (setup.py) ... done
  Created wheel for Certipy: filename=Certipy-3.0.0-py3-none-any.whl size=62389 sha256=99d5472cea3845d7e0976558595c6cd6466165cb85401e97de1adea557622db5
  Stored in directory: /tmp/pip-ephem-wheel-cache-v3uj41um/wheels/ae/be/17/5e122ae3e94c957008a4503a0a0c47d7982e744809a7e4d12a
Successfully built Certipy
Installing collected packages: Certipy
  Attempting uninstall: Certipy
    Found existing installation: Certipy 3.0.0
    Uninstalling Certipy-3.0.0:
      Successfully uninstalled Certipy-3.0.0
Successfully installed Certipy-3.0.0
===========================================================================
Error
===========================================================================                                                                                                                                                      
┌──(root💀CaptainPing)-[~/Desktop/Certipy]
└─# certipy           
Traceback (most recent call last):
  File "/usr/local/bin/certipy", line 5, in <module>
    from certipy.entry import main
ModuleNotFoundError: No module named 'certipy.entry'
