### ISSUE TITLE
[-] Received unknown error: (constraintViolation) 0000200B: AtrErr: DSID-033E0F1

### ISSUE THREAD

**Issue by zxcvbn001** [ly4k/Certipy#53]
Hello my brother, when using your tool to create a machine user remotely, an unknown error is reported

Certipy v3.0.0 - by Oliver Lyak (ly4k)

[+] Trying to resolve 'DC01.test.local' at '192.168.160.139'
[+] Authenticating to LDAP server
[+] Bound to ldaps://192.168.160.139:636 - ssl
[+] Default path: DC=test,DC=local
[+] Configuration path: CN=Configuration,DC=test,DC=local
[*] Creating new account:
    sAMAccountName                      : JACK-PC1$
    unicodePwd                          : LUCFG2bR2ARmhtkE
    userAccountControl                  : 4096
    servicePrincipalName                : HOST/JACK-PC1
                                          RestrictedKrbHost/JACK-PC1
    dnsHostName                         : 'DC01.test.local'
[-] Received unknown error: (constraintViolation) 0000200B: AtrErr: DSID-033E0F1
B, #1:
        0: 0000200B: DSID-033E0F1B, problem 1005 (CONSTRAINT_ATT_TYPE), data 0,
Att 9026b (dNSHostName)

![image](https://user-images.githubusercontent.com/23741141/169764887-ba485344-d348-4ac5-aa2c-9b25609cfdae.png)

**Comment by pingpongcult** [comment]
i also have thins problem, test on windows server 2012, 2016, 2019

**Comment by ThisIsN3w** [comment]
windows下去掉单引号，或者改成双引号。

**Comment by ly4k** [comment]
Hello
This means the domain controller has been patched and you can therefore not create a machine account with the same dns host name as the domain controller
