### ISSUE TITLE
certificate template is not supported by this CA

### ISSUE THREAD

**Issue by TryA9ain** [ly4k/Certipy#56]
I see #51, you say "If you want to setup your DC for Kerberos authentication with certificates, you need to request the certificate template "Kerberos" for your DC computer account".

I try it
`proxychains4 certipy req -dc-ip 192.168.1.2 "missyou.com/test1234$:test123456Aa@WIN-2012.missyou.com" -ca missyou-WIN-2012-CA-1 -template Kerberos -debug`

but tips Error
 "[-] Got error while trying to request certificate: code: 0x80094800 - CERTSRV_E_UNSUPPORTED_CERT_TYPE - The requested certificate template is not supported by this CA."

<img width="624" alt="image" src="https://user-images.githubusercontent.com/51145610/172291142-4949c9aa-0d4e-4cf8-977e-c928ba1044b1.png">

**Comment by ly4k** [comment]
Hello. The Kerberos certificate template should be requested by logging on to the DC, then open "mmc.exe", add the snap-in "Certificates" and choose "Local Computer". Then you can go to Certificates -> Personal and request the certificate
