### ISSUE TITLE
Incorrect user label for computer nodes with certificate permissions

### ISSUE THREAD

**Issue by uidzeroo** [ly4k/Certipy#61]
Hello,
when importing the data into Bloodhound, the label User is sometimes set additionally at computer nodes. As far as I could trace in the code, it is assumed that only groups or a users can have owner or enrollment permissions.  But it is also possible for other objects like computers. The affected code snippets are probably these: 

https://github.com/ly4k/Certipy/blob/7cadb2d63d7a4cd008a49f0533bf018b48f29482/certipy/find.py#L566
https://github.com/ly4k/Certipy/blob/7cadb2d63d7a4cd008a49f0533bf018b48f29482/certipy/find.py#L581

The result for a computer object in neo4j looks like this:
```
{
  "identity": 1337,
  "labels": [
    "Base",
    "User",
    "Computer"
  ],
...
```

This also leads to the fact that these computers are displayed as users in Bloodhound.

**Comment by ly4k** [comment]
Hello @uidzeroo This issue has already been mentioned in #50 and it will be fixed in the upcoming version of Certipy. Thanks for reporting it!

**Comment by ly4k** [comment]
Fixed in https://github.com/ly4k/Certipy/commit/defd7f458d8287ed4dc72c5d3164e507d2df3bd9
