### ISSUE TITLE
ESC1

### ISSUE THREAD

**Issue by danti1988** [ly4k/Certipy#68]
ESC1 is missing the -target parameter in the example. https://github.com/ly4k/Certipy#esc1

**Comment by ly4k** [comment]
Hello @danti1988 Thanks for reporting this. In my local setup, the CA is installed on the DC, so the target will be derived from the domain only, but I see that it can create some confusion, and I'll fix that in a bit. Thanks for reporting!

**Comment by ly4k** [comment]
Fixed in https://github.com/ly4k/Certipy/commit/3843eec3f014de2372e4260dddf5ffce9f0e95d0 Thank you
