### ISSUE TITLE
ESC9 failing for me - Probably incorrectly configured conditions

### ISSUE THREAD

**Issue by jsdhasfedssad** [ly4k/Certipy#75]
Hi,

I have successfully tested both cases of ESC10. Great work! However, when I try test ESC9 after patching I get the error below:
![certipy2](https://user-images.githubusercontent.com/97032878/183912618-7de6a0e2-a8a1-4428-92ce-f516680b7d72.png)

Template ESC9 is vulnerable to ESC9 according to Certipy:
![certipy3](https://user-images.githubusercontent.com/97032878/183914086-dcf7fbc8-8fb0-4353-a7b3-b54446224a94.png)

If this is not an error in the Certipy code, could you verify that I configured the DC correctly please?
- I have edited the registry key "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Kdc\StrongCertificateBindingEnforcement" from "1" to "2 (0x00000002). 
- I have set the flag "msPKI-Enrollment-Flag" on the certificate template ESC9 to "CT_FLAG_NO_SECURITY_EXTENSION" by executing the command "certutil -dstemplate ESC9 msPKI-Enrollment-Flag +0x00080000" in a elevated command prompt on the DC:
![certipy4](https://user-images.githubusercontent.com/97032878/183914927-0a79ec63-1d73-4862-9817-d02ac129b185.png)

**Comment by ly4k** [comment]
Hello @jsdhasfedssad StrongCertificateBindingEnforcement should be set to 0 and not 2. 2 is the most secure option whereas 0 is disabling the extension :-)

**Comment by jsdhasfedssad** [comment]
My bad, as I thought :) I had the wrong value on the key StrongCertificateBindingEnforcement. Closing.

**Comment by jsdhasfedssad** [comment]
Closing.
