### ISSUE TITLE
Allow specifying password when forging certificate using stolen CA cert

### ISSUE THREAD

**Issue by nickzer0** [ly4k/Certipy#80]
There is currently no way for me to specify a password for a stolen CA cert so that I can generate forged certificates using this cert. In order to forge the cert, I had to re-export the CA certificate without a password. 

Would it be possible to add a flag for the forge module to specify the certificate password? Thanks!

```
Certipy v3.0.0 - by Oliver Lyak (ly4k)

usage: certipy forge [-h] -ca-pfx pfx/p12 file name -alt alternative UPN [-template pfx/p12 file name] [-subject subject] [-crl ldap path] [-serial serial number]
                     [-debug] [-out output file name]

optional arguments:
  -h, --help            show this help message and exit
  -ca-pfx pfx/p12 file name
                        Path to CA certificate
  -alt alternative UPN
  -template pfx/p12 file name
                        Path to template certificate
  -subject subject      Subject to include certificate
  -crl ldap path        ldap path to a CRL
  -serial serial number
  -debug                Turn debug output on
```

**Comment by Gomez0015** [comment]
Feature added here : [PR](https://github.com/ly4k/Certipy/pull/98)

(only on "certipy req" for now but can be applied to anything including forge)

**Comment by ly4k** [comment]
Hello. Certipy already has built-in functionality to reexport a PFX file without a password. See the `certipy cert` command. I'll definitely have this option in mind though.

**Comment by Gomez0015** [comment]
@ly4k I think he wanted to specify a password, since it is forced without a password as of now
