### ISSUE TITLE
Unable to import data in bloodhound

### ISSUE THREAD

**Issue by 13375nip3r** [ly4k/Certipy#85]
The data collected cant be imported in the latest version of bloodhound. Is there a specific version of bloodhound i should be using. The error i get is "Invalid File Type"

**Comment by ly4k** [comment]
Hello @13375nip3r The mainstream BloodHound does not have support for ADCS. So you can either use my fork of BloodHound, or you can use "-old-bloodhound" when running the "find" command to use the data in the mainstream BloodHound

**Comment by ly4k** [comment]
Please see the "Find" section in Certipy's README
