### ISSUE TITLE
Wrong Certipy 

### ISSUE THREAD

**Issue by mellonaut** [ly4k/Certipy#94]
Having an issue with installing/running on Kali 2022.3 and could use some help.
If I try to run "certipy", I get asked if I want to install a certipy that is for making self-signed certificates. I say No.
From both the repo and the release, I install via pip or setup.py, and when I try to run 'certipy' it's the one I mentioned earlier, without the options or help menu from this certipy. If I go into /usr/local/lib/python3.10/dist-packages I can see Certipy 4.0 but I also see certipy that gets downloaded too. What's a good way to resolve this or where should I look for the file to run? I see an entry.py but I get errors when I try and just run that. Feel a little lost, thanks in advance

**Comment by Menn1s** [comment]
This issue almost drove me insane just now.. Not sure why it is the way it is, but using just pip3 to install it worked for me. So pip3 [pathToCertipy].

If you already tried that, make sure you run `which certipy` and remove the old one.

Anyway, hope that helps.

**Comment by mellonaut** [comment]
Gentleman && Scholar, appreciate!


________________________________
